---
- name: Ask AI to choose ONE allowed job template 
  hosts: localhost
  gather_facts: false

  vars:
    tower: "ATX"

    allowed_templates:
      - name: "Restart Cell Tower"
        description: "Restarts cell towers"
      - name: "setup-cell-tower"
        description: "Checks for configuration drift and resets to known good config"
      - name: "Failover to Next Neighbor"
        description: "Sends calls to nearest neighbor"

    # OpenAI settings
    openai_model: "gpt-4.1"
    openai_endpoint: "https://api.openai.com/v1/responses"
    openai_api_key: "{{ lookup('env', 'OPENAI_API_KEY') }}"

    schema_name: "choose_template"

  tasks:
    - name: Ensure OPENAI_API_KEY is set
      ansible.builtin.assert:
        that:
          - openai_api_key | length > 0
        fail_msg: "Set OPENAI_API_KEY in your environment before running."

    - name: Format allowed playbooks for prompt
      ansible.builtin.set_fact:
        allowed_templates_text: |-
          {% for p in allowed_templates %}
          - {{ p.name }} - {{ p.description }}
          {% endfor %}

    - name: Build AI prompt (exact structure)
      ansible.builtin.set_fact:
        ai_prompt: |-
          You are an automation assistant for telecom network operations.

          Your job is to select ONE playbook from the allowed list.

          Do not create new playbooks.
          Do not invent commands.
          Only return a valid JSON object.

          Event Context:
          {{ event_summary }}

          Allowed Playbooks:
          {{ allowed_templates_text }}

          Return format:
          {
            "recommended_template": "<playbook_name>",
            "reason": "<detailed explanation>"
          }

    - name: Build schema with enum restricted to allowed playbook names
      ansible.builtin.set_fact:
        allowed_names: "{{ allowed_templates | map(attribute='name') | list }}"
        output_schema:
          type: object
          additionalProperties: false
          properties:
            recommended_template:
              type: string
              enum: "{{ allowed_templates | map(attribute='name') | list }}"
            reason:
              type: string
          required:
            - recommended_template
            - reason

    - name: Call OpenAI Responses API with Structured Outputs
      ansible.builtin.uri:
        url: "{{ openai_endpoint }}"
        method: POST
        headers:
          Authorization: "Bearer {{ openai_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          model: "{{ openai_model }}"
          input:
            - role: "user"
              content:
                - type: "input_text"
                  text: "{{ ai_prompt }}"
          text:
            format:
              type: "json_schema"
              name: "{{ schema_name }}"
              strict: true
              schema: "{{ output_schema }}"
        return_content: true
        status_code: 200
      register: openai_resp

    - name: Extract model JSON text
      ansible.builtin.set_fact:
        ai_decision: "{{ openai_resp.json.output[0].content[0].text | default('') }}"

    - name: Show AI decision
      ansible.builtin.debug:
        msg:
          - "recommended_template: {{ ai_decision.recommended_template }}"
          - "reason: {{ ai_decision.reason }}"

    - name: Ensure recommendeded template is allowed
      ansible.builtin.assert:
        that:
          - ai_decision.recommended_template in allowed_names
        fail_msg: "AI returned a template not in the allowed list."

    - set_stats:
        data:
          recommended_template: "{{ ai_decision.recommended_template }}"
          reason: "{{ ai_decision.reason }}"

