---
- name: Ask AI to choose ONE allowed playbook (no log capture)
  hosts: localhost
  gather_facts: false

  vars:
    tower: "ATX"
    event_summary: |
      2026-02-16T20:41:12Z ALERT tower=ATX signal=dropped_calls value=0.14 threshold=0.05 window=5m
      2026-02-16T20:41:13Z CHECK connectivity ping=ok ssh=ok
      2026-02-16T20:41:14Z METRIC prb_utilization=38% congestion=false
      2026-02-16T20:41:15Z CONFIG admission_control max_calls_allowed=3 baseline=150
      2026-02-16T20:41:16Z WARN admission_reject_rate=82% reason="call_limit_exceeded"
      2026-02-16T20:41:17Z AUDIT config_change user=fieldtech12 change="max_calls_allowed set to 3"
      2026-02-16T20:41:20Z INFO neighbor_cells overloaded=false available_capacity=medium

    allowed_playbooks:
      - name: "restart_cell.tower.yml"
        description: "Restarts cell towers"
      - name: "reconfig_tower.yml"
        description: "Checks for configuration drift and resets to known good config"
      - name: "failover_next_neighbor"
        description: "Sends calls to nearest neighbor"

    # OpenAI settings
    openai_model: "gpt-4.1"
    openai_endpoint: "https://api.openai.com/v1/responses"
    openai_api_key: "{{ lookup('env', 'OPENAI_API_KEY') }}"

    schema_name: "choose_playbook"

  tasks:
    - name: Ensure OPENAI_API_KEY is set
      ansible.builtin.assert:
        that:
          - openai_api_key | length > 0
        fail_msg: "Set OPENAI_API_KEY in your environment before running."

    - name: Format allowed playbooks for prompt
      ansible.builtin.set_fact:
        allowed_playbooks_text: |-
          {% for p in allowed_playbooks %}
          - {{ p.name }} - {{ p.description }}
          {% endfor %}

    - name: Build AI prompt (exact structure)
      ansible.builtin.set_fact:
        ai_prompt: |-
          You are an automation assistant for telecom network operations.

          Your job is to select ONE playbook from the allowed list.

          Do not create new playbooks.
          Do not invent commands.
          Only return a valid JSON object.

          Event Context:
          {{ event_summary }}

          Allowed Playbooks:
          {{ allowed_playbooks_text }}

          Return format:
          {
            "recommended_playbook": "<playbook_name>",
            "reason": "<detailed explanation>"
          }

    - name: Build schema with enum restricted to allowed playbook names
      ansible.builtin.set_fact:
        allowed_names: "{{ allowed_playbooks | map(attribute='name') | list }}"
        output_schema:
          type: object
          additionalProperties: false
          properties:
            recommended_playbook:
              type: string
              enum: "{{ allowed_playbooks | map(attribute='name') | list }}"
            reason:
              type: string
          required:
            - recommended_playbook
            - reason

    - name: Call OpenAI Responses API with Structured Outputs
      ansible.builtin.uri:
        url: "{{ openai_endpoint }}"
        method: POST
        headers:
          Authorization: "Bearer {{ openai_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          model: "{{ openai_model }}"
          input:
            - role: "user"
              content:
                - type: "input_text"
                  text: "{{ ai_prompt }}"
          text:
            format:
              type: "json_schema"
              name: "{{ schema_name }}"
              strict: true
              schema: "{{ output_schema }}"
        return_content: true
        status_code: 200
      register: openai_resp

    - name: Extract model JSON text
      ansible.builtin.set_fact:
        ai_decision: "{{ openai_resp.json.output[0].content[0].text | default('') }}"

    - name: Show AI decision
      ansible.builtin.debug:
        msg:
          - "recommended_playbook: {{ ai_decision.recommended_playbook }}"
          - "reason: {{ ai_decision.reason }}"

    - name: ensure recommended playbook is allowed
      ansible.builtin.assert:
        that:
          - ai_decision.recommended_playbook in allowed_names
        fail_msg: "AI returned a playbook not in the allowed list."
