---
- name: Send Slack approval request
  hosts: localhost
  gather_facts: false

  vars:
    # Provide these via AAP extra_vars or credentials
    cell_id: "ATX"
    recommended_playbook: "{{ recommended_playbook }}"
    reason: "{{ reason }}"

  tasks:
    - name: Build workflow approval link
      set_fact:
        approval_link: "{{ lookup('env', 'AAP_HOSTNAME') }}/execution/administration/workflow-approvals"

    - name: Build Slack blocks
      ansible.builtin.set_fact:
        slack_blocks:
          - type: header
            text:
              type: plain_text
              text: "Approval Needed: Recommended Remediation"
          - type: section
            fields:
              - type: mrkdwn
                text: "*Cell/Tower:*\n{{ cell_id }}"
              - type: mrkdwn
                text: "*Playbook:*\n`{{ recommended_playbook }}`"
          - type: section
            text:
              type: mrkdwn
              text: "*Why this playbook:*\n{{ reason }}"
          - type: section
            text:
              type: mrkdwn
              text: "<{{ approval_link }}|Open in AAP to Approve>"

    
    - name: Send Slack message (incoming webhook)
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "Approval Needed: Recommended Remediation"
          blocks: "{{ slack_blocks }}"
        status_code: 200
      register: slack_resp

    - name: Log Slack response (debug)
      ansible.builtin.debug:
        var: slack_resp.status
